# Generated by Django 4.1.2 on 2022-10-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_add', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='IPClientVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas', models.IntegerField(default=0)),
                ('ip_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.ipclient')),
            ],
        ),
    ]
