# Generated by Django 4.1.7 on 2023-02-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPUsers',
            fields=[
                ('ip', models.AutoField(db_column='IP', primary_key=True, serialize=False, verbose_name='IP_ID')),
                ('browser', models.CharField(db_column='Browser', max_length=255, verbose_name='Browser')),
                ('first_time', models.DateTimeField(auto_now_add=True, db_column='First Time', verbose_name='First Time')),
                ('last_time', models.DateTimeField(auto_now=True, db_column='Last Time', verbose_name='Last Time')),
                ('visits', models.IntegerField(db_column='Visits', default=0, verbose_name='Visits')),
            ],
            options={
                'verbose_name': 'IP Users',
                'verbose_name_plural': 'IP Users',
            },
        ),
        migrations.RemoveField(
            model_name='ipclientvisitas',
            name='ip_key',
        ),
        migrations.DeleteModel(
            name='IPClient',
        ),
        migrations.DeleteModel(
            name='IPClientVisitas',
        ),
    ]
