# Generated by Django 4.1.7 on 2023-02-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_ipusers_remove_ipclientvisitas_ip_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipusers',
            name='ip',
            field=models.CharField(db_column='IP', max_length=255, primary_key=True, serialize=False, verbose_name='IP_ID'),
        ),
    ]
