# Generated by Django 4.1.7 on 2023-02-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0003_alter_ipusers_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipusers',
            name='country',
            field=models.CharField(db_column='Country', max_length=255, null=True, verbose_name='Country'),
        ),
    ]
