# Generated by Django 4.1.7 on 2023-02-28 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_ipusers_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_ip', models.CharField(db_column='Country', max_length=255, verbose_name='Country')),
                ('fk_ipuser', models.ForeignKey(db_column='Fk IPUsers', on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='portafolio.ipusers')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Data_of_IPUser_for_Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(db_column='latitude', max_length=255, verbose_name='Latitude')),
                ('lon', models.CharField(db_column='langitude', max_length=255, verbose_name='Longitude')),
                ('isp', models.CharField(db_column='ISP', max_length=255, verbose_name='ISP')),
                ('code_zip', models.CharField(db_column='CodePostal', max_length=60, verbose_name='Code Postal')),
                ('fk_countries', models.ForeignKey(db_column='FK_Countries', on_delete=django.db.models.deletion.CASCADE, to='portafolio.country')),
                ('fk_ipusers', models.ForeignKey(db_column='FK_IPUsers', on_delete=django.db.models.deletion.CASCADE, to='portafolio.ipusers')),
            ],
            options={
                'verbose_name': 'Data User Countrie',
                'verbose_name_plural': 'Datas Users Countries',
            },
        ),
    ]
