# Generated by Django 4.1.7 on 2023-02-28 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_remove_data_of_ipuser_for_country_fk_countries_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipusers',
            table='IPUsers',
        ),
    ]
