# Generated by Django 4.1.7 on 2023-02-28 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0007_alter_ipusers_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ipusers',
            table=None,
        ),
    ]
