# Generated by Django 4.1.2 on 2022-12-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='alt_image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(max_length=2000),
        ),
    ]
