# Generated by Django 4.1.2 on 2022-12-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='alt_image',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
