# Generated by Django 4.1.2 on 2022-12-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_articulo_alt_image_alter_articulo_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
