# Generated by Django 4.1.2 on 2022-12-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_created_articulo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='date',
            new_name='created',
        ),
    ]
