# Generated by Django 4.1.2 on 2022-12-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_date_articulo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='priority',
            field=models.IntegerField(default=0.5),
        ),
    ]
