# Generated by Django 4.1.2 on 2022-12-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articulo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='priority',
            field=models.FloatField(default=0.5),
        ),
    ]
