# Generated by Django 4.1.2 on 2022-12-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_articulo_contenido_alter_articulo_titulo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
