# Generated by Django 4.1.2 on 2022-12-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_articulo_contenido_alter_articulo_titulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='Prioridad',
            new_name='prioridad',
        ),
    ]
