# Generated by Django 4.1.2 on 2022-12-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_prioridad_articulo_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='description',
            field=models.CharField(max_length=360, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='tags',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
