# Generated by Django 4.1.2 on 2022-12-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_articulo_description_articulo_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='description',
            field=models.TextField(max_length=360, null=True),
        ),
    ]
