# Generated by Django 4.1.2 on 2023-01-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_articulo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=200)),
                ('navigator', models.CharField(max_length=256)),
                ('one_visit', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_visit', models.DateField(auto_now=True, null=True)),
                ('visits', models.IntegerField(default=0)),
            ],
        ),
    ]
