# Generated by Django 4.1.2 on 2023-01-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_ipusuarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipusuarios',
            name='ip',
            field=models.CharField(max_length=200, verbose_name='IP del Usuario'),
        ),
        migrations.AlterField(
            model_name='ipusuarios',
            name='last_visit',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Última Visita'),
        ),
        migrations.AlterField(
            model_name='ipusuarios',
            name='navigator',
            field=models.CharField(max_length=256, verbose_name='Navegador, OS y más'),
        ),
        migrations.AlterField(
            model_name='ipusuarios',
            name='one_visit',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Primer Visita'),
        ),
        migrations.AlterField(
            model_name='ipusuarios',
            name='visits',
            field=models.IntegerField(default=0, verbose_name='Total de Visitas'),
        ),
    ]
