# Generated by Django 4.1.2 on 2023-01-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_ipusuarios_ip_alter_ipusuarios_last_visit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ipusuarios',
            options={'verbose_name': 'Usuarios IP', 'verbose_name_plural': 'Usuarios IP'},
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='last_url',
            field=models.CharField(max_length=500, null=True, verbose_name='Última URL Visitada'),
        ),
        migrations.AlterField(
            model_name='ipusuarios',
            name='ip',
            field=models.CharField(max_length=200, null=True, verbose_name='IP del Usuario'),
        ),
        migrations.AlterField(
            model_name='ipusuarios',
            name='navigator',
            field=models.CharField(max_length=256, null=True, verbose_name='Navegador, OS y más'),
        ),
        migrations.AlterField(
            model_name='ipusuarios',
            name='visits',
            field=models.IntegerField(default=0, null=True, verbose_name='Total de Visitas'),
        ),
    ]
