# Generated by Django 4.1.2 on 2023-01-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_ipusuarios_options_ipusuarios_last_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipusuarios',
            name='code_status',
            field=models.IntegerField(default=0, null=True, verbose_name='Codigo de respuesta'),
        ),
    ]
