# Generated by Django 4.1.2 on 2023-01-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_ipusuarios_code_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipusuarios',
            name='last_url',
        ),
    ]
