# Generated by Django 4.1.7 on 2023-02-28 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_ipusuarios_last_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='autor',
            field=models.CharField(default='Estuardo Ramírez', max_length=200),
        ),
        migrations.AddField(
            model_name='articulo',
            name='visits',
            field=models.IntegerField(default=0, null=True, verbose_name='Total Visitas'),
        ),
    ]
