# Generated by Django 4.1.7 on 2023-02-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_articulo_autor_articulo_visits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipusuarios',
            name='code_status',
        ),
        migrations.RemoveField(
            model_name='ipusuarios',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='ipusuarios',
            name='navigator',
        ),
        migrations.RemoveField(
            model_name='ipusuarios',
            name='one_visit',
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='browser',
            field=models.CharField(db_column='Browser', max_length=255, null=True, verbose_name='Browser'),
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='city',
            field=models.CharField(db_column='City', max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='code_zip',
            field=models.CharField(db_column='CodePostal', max_length=60, null=True, verbose_name='Code Postal'),
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='country',
            field=models.CharField(db_column='Country', max_length=255, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='first_time',
            field=models.DateTimeField(auto_now_add=True, db_column='First Time', null=True, verbose_name='First Time'),
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='isp',
            field=models.CharField(db_column='ISP', max_length=255, null=True, verbose_name='ISP'),
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='last_time',
            field=models.DateTimeField(auto_now=True, db_column='Last Time', null=True, verbose_name='Last Time'),
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='lat',
            field=models.CharField(db_column='latitude', max_length=255, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='ipusuarios',
            name='lon',
            field=models.CharField(db_column='langitude', max_length=255, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='ipusuarios',
            name='visits',
            field=models.IntegerField(db_column='Visits', default=0, null=True, verbose_name='Visits'),
        ),
    ]
