# Generated by Django 4.1.7 on 2023-04-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_ipusuarios_code_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='alt_imagen',
            new_name='alt_image',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='creado',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='creado_el',
            new_name='date_create',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='imagen',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='prioridad',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='titulo',
            new_name='tittle',
        ),
    ]
